version: '3.8'

services:
  minedock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minedock
    ports:
      - "${MINECRAFT_PORT:-25565}:${MINECRAFT_PORT:-25565}" # Définit un port par défaut
    volumes:
      - ./data:/data # Persistance des données du serveur
      - ./server.properties.template:/home/minecraft/server.properties.template # Template pour la config
    restart: unless-stopped
    environment:
      - VERSION=${https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar}
      - MEMORY=${MEMORY:-8192} # Mémoire par défaut à 1024 Mo
      - EULA=${EULA:-false}
      - LEVEL_SEED=${LEVEL_SEED:-}
      - GAMEMODE=${GAMEMODE:-survival}
      - LEVEL_NAME=${LEVEL_NAME:-world}
      - MOTD=${MOTD:-A Minecraft Server}
      - DIFFICULTY=${DIFFICULTY:-hard}
      - MAX_PLAYERS=${MAX_PLAYERS:-10}

